//default [light mode] theme
import 'package:flutter/material.dart';
import 'package:pomodoro/theme_stuff/colours.dart';

ThemeData defaultTheme = ThemeData(
  brightness: Brightness.light,
  // primaryColor: Colours.PRIMARY_COLOR,
  // primarySwatch: Colours.PRIMARY_SWATCH,
  useMaterial3: true,
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF6F48B2),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFEBDCFF),
    onPrimaryContainer: Color(0xFF260058),
    secondary: Color(0xFF635B70),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFEADEF7),
    onSecondaryContainer: Color(0xFF1F182A),
    tertiary: Color(0xFF7F525D),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD9E0),
    onTertiaryContainer: Color(0xFF32101A),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1D1B1E),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF1D1B1E),
    surfaceVariant: Color(0xFFE7E0EB),
    onSurfaceVariant: Color(0xFF49454E),
    outline: Color(0xFF7A757F),
    onInverseSurface: Color(0xFFF5EFF4),
    inverseSurface: Color(0xFF323033),
    inversePrimary: Color(0xFFD4BBFF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF6F48B2),
    outlineVariant: Color(0xFFCBC4CF),
    scrim: Color(0xFF000000),
  ),
);

ThemeData darkTheme = ThemeData(
    brightness: Brightness.dark,
    // primaryColor: Colours.PRIMARY_DARK_COLOR,
    // primarySwatch: Colours.PRIMARY_DARK_SWATCH,
    // appBarTheme: const AppBarTheme(
    //   backgroundColor: Colours.PRIMARY_DARK_COLOR,
    // ),
    useMaterial3: true,
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD4BBFF),
      onPrimary: Color(0xFF3F0F81),
      primaryContainer: Color(0xFF572E99),
      onPrimaryContainer: Color(0xFFEBDCFF),
      secondary: Color(0xFFCDC2DB),
      onSecondary: Color(0xFF342D40),
      secondaryContainer: Color(0xFF4B4358),
      onSecondaryContainer: Color(0xFFEADEF7),
      tertiary: Color(0xFFF1B7C4),
      onTertiary: Color(0xFF4A252F),
      tertiaryContainer: Color(0xFF643B45),
      onTertiaryContainer: Color(0xFFFFD9E0),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1D1B1E),
      onBackground: Color(0xFFE6E1E6),
      surface: Color(0xFF1D1B1E),
      onSurface: Color(0xFFE6E1E6),
      surfaceVariant: Color(0xFF49454E),
      onSurfaceVariant: Color(0xFFCBC4CF),
      outline: Color(0xFF948E99),
      onInverseSurface: Color(0xFF1D1B1E),
      inverseSurface: Color(0xFFE6E1E6),
      inversePrimary: Color(0xFF6F48B2),
      shadow: Color(0xFF000000),
      surfaceTint: Color(0xFFD4BBFF),
      outlineVariant: Color(0xFF49454E),
      scrim: Color(0xFF000000),
    ));
